spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ben.ferenchak
    password: rsmiypjkaiocbbbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true